use classicmodels;

SELECT customerName,customerNumber from customers;
select * from customers;
select phone from customers;
select  customerName,phone,creditLimit from customers;
select customerName,addressLine1,city,postalCode from customers;
select customerName,salesRepEmployeeNumber from customers;
select  customerName,phone from customers order by customerName;
select customerName,creditLimit from customers order by customerName;
select customerName,city,state,country from customers order by customerName;
select customerName,creditLimit from customers order by creditLimit;
select customerName,phone,creditLimit from customers where creditLimit>40000;
select  firstName,jobTitle from employees;
select productName;
select * from offices;
select * from orders;
select *from orders;
select*from payments;
select * from products;
select * from products where MSRP>100;
select *from employees;
insert into employees(employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle) values(007,'Asokan','NA','x01234','pradeepaokan@outlook.com',5,1143,'trainee');
select * from employees where employeeNumber=007;
insert into cuscustomerstomers (customerNumber,customerName,contactLastName,contactFirstName,phone,addressLine1,addressLine2,city,state,postalCode,country,salesRepEmployeeNumber,creditLimit) values (007,'pradeep','Asokan','A',9080325217,'5/71 ganthinagar','NA','erode','TN',638008,'India',007,100000);
insert into offices(officeCode,city,phone,addressLine1,addressLine2,state,country,postalCode,territory) values ('002255','erode','9080325217','5/71 ganthinagar','NA','TN','India','638008','NA');
select * from offices;
select * from orders;
insert into orders(orderNumber,orderDate,requiredDate,shippedDate,status,comments,customerNumber) values(117,'2021-02-15' ,'2021-02-18','2021-02-16','shipped','null',007);
select * from customers where customerNumber=007;
select * from customers where creditLimit>75000;
SET SQL_SAFE_UPDATES=0;
delete from offices where officeCode=00255 ;
select * from offices;
select * from employees;
select * from customers where city='erode';
select *from offices;
select *from employees where jobTitle='trainee';
update customers set customerName='Pradeep' where phone='9080325217';

